CollectionsProject/Controllers/CollectionController.cs
using CollectionsProject.Models.UserModels;
using CollectionsProject.Services.Interfaces;
using CollectionsProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Collection = CollectionsProject.Models.CollectionModels.Collection;
using CollectionsProject.Repositories.Interfaces;
using CollectionsProject.Extensions;

namespace CollectionsProject.Controllers
{
    [Authorize]
    public class CollectionController : Controller
    {
        private readonly ICollectionRepository _collectionRepository;
        private readonly IFileService _fileService;
        private readonly ICollectionService _collectionService;
        private readonly UserManager<User> _userManager;
        private const int itemsCount = 5;
        private const string noPhoto = "noPhoto.jpg";

        public CollectionController(ICollectionRepository collectionRepository, UserManager<User> userManager
            , IFileService fileService, ICollectionService collectionService)
        {
            _collectionRepository = collectionRepository;
            _userManager = userManager;
            _fileService = fileService;
            _collectionService = collectionService;
        }

        //Personal page of collection
        [HttpGet]
        public IActionResult Index() => View();

        [HttpGet]
        public IActionResult Create() => View();

        //List of collections to view
        [HttpGet]
        [AllowAnonymous]
        public IActionResult CollectionList() => View();

        //Add field to new collection
        [HttpGet]
        public IActionResult AddNewField(int i = 0) => PartialView("AddNewField", i);

        [HttpPost]
        public async Task<IActionResult> Create(CollectionViewModel model, IFormFile? formFile = null)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _userManager.GetUserAsync(User);
                model.Image = noPhoto;
                if (formFile != null) //user uploaded the image
                    model.Image = await _fileService.CreateFileAsync(formFile);
                var collection = _collectionService.CreateNewCollection(model, currentUser);
                _collectionRepository.Create(collection);
                if (model.CustomFields != null) //if user added custom fields
                {
                    var fields = _collectionService.CreateAddFields(model.CustomFields, collection);
                    _collectionRepository.AddFieldsRange(fields);
                }
                await _collectionRepository.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            var collection = await _collectionRepository.GetItemAsync(id);
            if (collection == null)
                return NotFound();
            if (!this.HasAccess(collection.User.UserName))
                return Forbid();
            _collectionRepository.Delete(collection);
            if (collection.Image != noPhoto)
                _fileService.DeleteFile(collection.Image);
            await _collectionRepository.SaveChangesAsync();
            return new OkResult();
        }

        [HttpGet]
        public IActionResult Update() => PartialView();

        [HttpPost]
        public async Task<IActionResult> Update(CollectionViewModel model, IFormFile? formFile = null)
        {
            if (ModelState.IsValid)
            {
                var collection = await _collectionRepository.GetItemAsync(model.Id);
                if (collection == null)
                    return NotFound();
                if (!this.HasAccess(collection.User.UserName))
                    return Forbid();
                collection.Description = model.Description;
                collection.Name = model.Name;
                collection.Type = model.Type;

                if (formFile != null) //new image was uploaded otherwise previous image will be remained
                    collection.Image = await _fileService.UpdateFileAsync(formFile, collection.Image);
                _collectionRepository.Update(collection);
                await _collectionRepository.SaveChangesAsync();
                return PartialView("CollectionPage", new List<Collection>() { collection });
            }
            return BadRequest();
        }

        //Personal Page controller of current user
        [HttpPost]
        public async Task<IActionResult> PersonalPage(int id = 0)
        {
            var user = await _userManager.GetUserAsync(User);
            var collections = await _collectionRepository.GetUserItemsAsync(id * itemsCount, itemsCount, user.Id);
            return PartialView("CollectionPage", collections);
        }

        //Calculate Pages for items in pagination
        private static int CountPagesInItems(int collectionCount)
        {
            if (collectionCount % itemsCount == 0)
                return collectionCount / itemsCount;
            return collectionCount / itemsCount + 1;
        }

        //Items of corresponding collection
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> CollectionItems(string id)
        {
            var result = await _collectionRepository.GetItemAsync(id);
            if (result == null)
                return NotFound();
            var count = await _collectionService.GetItemCountAsync(id);
            ViewBag.ItemPerPage = CountPagesInItems(count);
            return View(result);
        }

        //Page of collections ordered by Id
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> CollectionPage(int id = 0)
        {
            var collections = await _collectionRepository.GetSomeItemsAsync(id * itemsCount, itemsCount);
            return PartialView("CollectionPage", collections);
        }
    }
}

CollectionsProject/Controllers/SearchController.cs
using CollectionsProject.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace CollectionsProject.Controllers
{
    public class SearchController : Controller
    {
        private readonly IFullTextSearch _fullTextSearch;

        public SearchController(IFullTextSearch fullTextSearch)
        {
            _fullTextSearch = fullTextSearch;
        }

        //full text search action
        [HttpPost]
        public async Task<IActionResult> Search(string searchString)
        {
            //search limit (ex MySQL won't find text less than 3 symbols)
            if (string.IsNullOrEmpty(searchString) || searchString.Length<3) 
                return BadRequest();
            string requireWord = '+' + searchString; // '+' means require word (in MySql in Boolean mode)
            ViewBag.Items = await _fullTextSearch.SearchInItems(requireWord);
            ViewBag.Collections = await _fullTextSearch.SearchInCollections(requireWord);
            return PartialView();
        }
    }
}

CollectionsProject/Views/Shared/_Layout.cshtml
@{
    bool isAdmin = User.IsInRole("Admin");
    bool isAuthenticated = User.Identity!.IsAuthenticated;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CollectionsProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome-4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/@ViewBag.CssPath" asp-append-version="true" />
</head>
<body class="light-body">
    <div class="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <div class="navbar-collapse collapse d-inline-flex justify-content-between">
                        <div class="nav-theme-wrapper">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Index">@Loc["Home"]</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Collection" asp-action="CollectionList">@Loc["Collection List"]</a>
                                </li>
                                @if (isAuthenticated)
                                {
                                    @await RenderSectionAsync("Create", required: false)
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="Collection" asp-action="Index">@Loc["Personal Page"]</a>
                                    </li>
                                    @if (isAdmin)
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link" asp-controller="Admin" asp-action="UserManager">@Loc["User Panel"]</a>
                                        </li>
                                    }
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="Account" asp-action="Logout">@Loc["Log Out"]</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="Account" asp-action="Register">@Loc["Register"]</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-controller="Account" asp-action="Login">@Loc["Login"]</a>
                                    </li>
                                }
                            </ul>
                            <nav id="pop-up-menu" class="pop-up-menu">
                                <ul class="pop-up-list">
                                    <li class="pop-up-item">
                                        <a class="pop-up-link" asp-controller="Home" asp-action="Index">@Loc["Home"]</a>
                                    </li>
                                    <li class="pop-up-item">
                                        <a class="pop-up-link" asp-controller="Collection" asp-action="CollectionList">@Loc["Collection List"]</a>
                                    </li>
                                    @if (isAuthenticated)
                                    {
                                        @await RenderSectionAsync("CreatePopUp", required: false)
                                        <li class="pop-up-item">
                                            <a class="pop-up-link" asp-controller="Collection" asp-action="Index">@Loc["Personal Page"]</a>
                                        </li>
                                        @if (isAdmin)
                                        {
                                            <li class="pop-up-item">
                                                <a class="pop-up-link" asp-controller="Admin" asp-action="UserManager">@Loc["User Panel"]</a>
                                            </li>
                                        }
                                        <li class="pop-up-item">
                                            <a class="pop-up-link" asp-controller="Account" asp-action="Logout">@Loc["Log Out"]</a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li class="pop-up-item">
                                            <a class="pop-up-link" asp-controller="Account" asp-action="Register">@Loc["Register"]</a>
                                        </li>
                                        <li class="pop-up-item">
                                            <a class="pop-up-link" asp-controller="Account" asp-action="Login">@Loc["Login"]</a>
                                        </li>
                                    }
                                </ul>
                            </nav>
                            <div id="pop-up-icon" class="pop-up_menu_sign">
                                <i class="fa fa-bars" aria-hidden="true"></i>
                            </div>
                            <div class="change-mode">
                                <label class="switch">
                                    <input type="checkbox" class="form-check" id="theme-switcher" />
                                    <span class="slider round"></span>
                                </label>
                            </div>
                        </div>
                        <div class="search-form">
                            <form method="POST" data-ajax-method="POST" data-ajax="true" asp-controller="Search" asp-action="Search" data-ajax-success="OnSearchSuccess">
                                <div class="form-group form-elements input-form-el">
                                    <label for="search-input">@Loc["Search"]:</label>
                                    <div id="search-group">
                                        <input type="text" id="search-input" name="searchString" autocomplete="off" required />
                                        <ul id="search-list">
                                        </ul>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-success btn-app" id="search-btn"><i class="fa fa-search" aria-hidden="true" hi></i></button>
                            </form>
                        </div>
                        <div class="link-language">
                            @await Html.PartialAsync("_SelectLanguagePartial")
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <div class="content container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        <footer class=" bg-white border-top footer text-muted">
            <div class="container">
                &copy; 2022 - CollectionsProject
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib//site-unobstrusive-dark.min.js" asp-append-version="true"></script>
    <script src="~/lib/Markdown/turndown.min.js"></script>
    @await RenderSectionAsync("ScriptsUpper", required: false)
    <script src="~/@ViewBag.JsPath" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CollectionsProject/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
        .ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@(Context.Request.Path+Context.Request.QueryString)" method="POST">
    <span>@Loc["Language"]</span>
    <select name="culture" onchange="this.form.submit();"
            asp-for="@requestCulture.RequestCulture.UICulture.Name"
            asp-items="cultureItems" class="form-select"></select>
</form>