CollectionsProject/Controllers/HomeController.cs
using CollectionsProject.Services.Interfaces;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionsProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHomeService _homeService;

        public HomeController(IHomeService homeService)
        {
            _homeService = homeService;
        }

        public async Task<IActionResult> Index()
        {
            var homeModel = await _homeService.GetHomeModel();
            return View(homeModel);
        }

        //set current site language
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1),
                    IsEssential = true
                }
            );
            return LocalRedirect(returnUrl);
        }
    }
}

CollectionsProject/Controllers/TagController.cs
using CollectionsProject.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionsProject.Controllers
{

    public class TagController : Controller
    {
        private readonly ITagRepository _tagRepository;
        private const int itemCount = 15;

        public TagController(ITagRepository tagRepository)
        {
            _tagRepository = tagRepository;
        }

        //tag for autocompletion
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> GetAllTags()
        {
            var tags = await _tagRepository.GetTagNamesAsync();
            return new JsonResult(tags);
        }

        //pagination for tag page with corresponding items
        [HttpPost]
        public async Task<IActionResult> ItemPage(string TagName, int Page = 0)
        {
            var items = await _tagRepository.GetTagItems(TagName, Page * itemCount, itemCount);
            return PartialView("~/Views/Item/ItemShortDescription.cshtml", items);
        }

        //tag page with items
        [HttpGet]
        public async Task<IActionResult> ItemList(string id) //id - tag name
        {
            var count = await _tagRepository.CountTagInItemsAsync(id);
            if (count == 0)
                return NotFound();
            return View("ItemList", id);
        }
    }
}

CollectionsProject/Views/Home/Index.cshtml
@model HomeModel
@{
    ViewData["Title"] = "Home Page";
    ViewBag.CssPath = "css/home.min.css";
    ViewBag.JsPath = "js/home.min.js";
    int timeNow = DateTime.UtcNow.Millisecond;
    Random rand = new Random(timeNow);
}
@section Scripts{
    <script>
        $("#tagcloud a").tagcloud({
            size: { start: 24, end: 36, unit: "px" },
            color: { start: '#3498DB', end: '#46CFB0' }
        });
    </script>
}
    <div class="home-container container">
        <div class="row">
            <h1 class="text-left" style="margin-bottom:5px">@Loc["Header_Item"]</h1>
            <table style="margin-top:0" class="col-8 table-collection-list table table-hover table-bordered text-center">
                <thead class="bg-info">
                    <tr>
                        <th>@Loc["Item_Name"]</th>
                        <th>@Loc["Collection_Name"]</th>
                        <th>@Loc["Author"]</th>
                        <th>@Loc["Action"]</th>
                    </tr>
                </thead>
                <tbody class="bg-light" id="tableBody">
                    @await Html.PartialAsync("~/Views/Item/ItemShortDescription.cshtml",Model.Items)
                </tbody>
            </table>
        </div>
        <div id="collection-list" class="container-fluid">
            <h1 class="text-left" style="margin-bottom:5px">@Loc["Header_Collection"]</h1>
            @await Html.PartialAsync("~/Views/Collection/CollectionPage.cshtml",Model.Collections)
        </div>
        @{
        if (Model.Tags != null)
        {
            <h1 style="margin-top:20px" class="text-left">@Loc["Header_Tags"]</h1>
            <div id="tagcloud" class="cloud-tags bg-light">
                @{
                    foreach (var tag in Model.Tags)
                    {
                        <a asp-controller="Tag" asp-action="ItemList" asp-route-id="@tag" rel="@rand.Next(timeNow)">@tag</a>
                    }
                }
            </div>
        }
    }
</div>
@await Html.PartialAsync("~/Views/Collection/Update.cshtml", new CollectionViewModel())