CollectionsProject/Models/CollectionModels/Collection.cs
using CollectionsProject.Models.ItemModels;
using CollectionsProject.Models.UserModels;

namespace CollectionsProject.Models.CollectionModels
{
    public class Collection
    {
        public Guid CollectionId { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string? Image { get; set; }
        public CollectionType Type { get; set; }
        public int Count { get; set; }

        public string UserId { get; set; } = null!;
        public User User { get; set; } = null!;

        public List<Item>? Items { get; set; }
        public List<AddCollectionField>? AddFields { get; set; }
    }
}

CollectionsProject/Models/CollectionModels/CollectionType.cs
using System.ComponentModel.DataAnnotations;

namespace CollectionsProject.Models.CollectionModels
{
    public enum CollectionType
    {
        [Display(Name = "Book")]
        Book,
        [Display(Name = "Sign")]
        Sign,
        [Display(Name = "Whiskey")]
        Whiskey,
    }
}

CollectionsProject/ViewModels/CollectionViewModel.cs
using CollectionsProject.Models.CollectionModels;
using System.ComponentModel.DataAnnotations;

namespace CollectionsProject.ViewModels
{
    public class CollectionViewModel
    {
        public string? Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [MaxLength(30, ErrorMessage = "Length should be less than 30")]
        public string Name { get; set; } = "";

        [Required(ErrorMessage = "Description is required")]
        [StringLength(300, ErrorMessage = ("Length should be less than 300"), MinimumLength = 1)]
        public string Description { get; set; } = "";

        [Required]
        public CollectionType Type { get; set; }

        public string? Image { get; set; }

        public List<CustomFieldViewModel>? CustomFields { get; set; }
    }
}

CollectionsProject/Controllers/CollectionController.cs
using CollectionsProject.Models.UserModels;
using CollectionsProject.Services.Interfaces;
using CollectionsProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Collection = CollectionsProject.Models.CollectionModels.Collection;
using CollectionsProject.Repositories.Interfaces;
using CollectionsProject.Extensions;

namespace CollectionsProject.Controllers
{
    [Authorize]
    public class CollectionController : Controller
    {
        private readonly ICollectionRepository _collectionRepository;
        private readonly IFileService _fileService;
        private readonly ICollectionService _collectionService;
        private readonly UserManager<User> _userManager;
        private const int itemsCount = 5;
        private const string noPhoto = "noPhoto.jpg";

        public CollectionController(ICollectionRepository collectionRepository, UserManager<User> userManager
            , IFileService fileService, ICollectionService collectionService)
        {
            _collectionRepository = collectionRepository;
            _userManager = userManager;
            _fileService = fileService;
            _collectionService = collectionService;
        }

        //Personal page of collection
        [HttpGet]
        public IActionResult Index() => View();

        [HttpGet]
        public IActionResult Create() => View();

        //List of collections to view
        [HttpGet]
        [AllowAnonymous]
        public IActionResult CollectionList() => View();

        //Add field to new collection
        [HttpGet]
        public IActionResult AddNewField(int i = 0) => PartialView("AddNewField", i);

        [HttpPost]
        public async Task<IActionResult> Create(CollectionViewModel model, IFormFile? formFile = null)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _userManager.GetUserAsync(User);
                model.Image = noPhoto;
                if (formFile != null) //user uploaded the image
                    model.Image = await _fileService.CreateFileAsync(formFile);
                var collection = _collectionService.CreateNewCollection(model, currentUser);
                _collectionRepository.Create(collection);
                if (model.CustomFields != null) //if user added custom fields
                {
                    var fields = _collectionService.CreateAddFields(model.CustomFields, collection);
                    _collectionRepository.AddFieldsRange(fields);
                }
                await _collectionRepository.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            var collection = await _collectionRepository.GetItemAsync(id);
            if (collection == null)
                return NotFound();
            if (!this.HasAccess(collection.User.UserName))
                return Forbid();
            _collectionRepository.Delete(collection);
            if (collection.Image != noPhoto)
                _fileService.DeleteFile(collection.Image);
            await _collectionRepository.SaveChangesAsync();
            return new OkResult();
        }

        [HttpGet]
        public IActionResult Update() => PartialView();

        [HttpPost]
        public async Task<IActionResult> Update(CollectionViewModel model, IFormFile? formFile = null)
        {
            if (ModelState.IsValid)
            {
                var collection = await _collectionRepository.GetItemAsync(model.Id);
                if (collection == null)
                    return NotFound();
                if (!this.HasAccess(collection.User.UserName))
                    return Forbid();
                collection.Description = model.Description;
                collection.Name = model.Name;
                collection.Type = model.Type;

                if (formFile != null) //new image was uploaded otherwise previous image will be remained
                    collection.Image = await _fileService.UpdateFileAsync(formFile, collection.Image);
                _collectionRepository.Update(collection);
                await _collectionRepository.SaveChangesAsync();
                return PartialView("CollectionPage", new List<Collection>() { collection });
            }
            return BadRequest();
        }

        //Personal Page controller of current user
        [HttpPost]
        public async Task<IActionResult> PersonalPage(int id = 0)
        {
            var user = await _userManager.GetUserAsync(User);
            var collections = await _collectionRepository.GetUserItemsAsync(id * itemsCount, itemsCount, user.Id);
            return PartialView("CollectionPage", collections);
        }

        //Calculate Pages for items in pagination
        private static int CountPagesInItems(int collectionCount)
        {
            if (collectionCount % itemsCount == 0)
                return collectionCount / itemsCount;
            return collectionCount / itemsCount + 1;
        }

        //Items of corresponding collection
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> CollectionItems(string id)
        {
            var result = await _collectionRepository.GetItemAsync(id);
            if (result == null)
                return NotFound();
            var count = await _collectionService.GetItemCountAsync(id);
            ViewBag.ItemPerPage = CountPagesInItems(count);
            return View(result);
        }

        //Page of collections ordered by Id
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> CollectionPage(int id = 0)
        {
            var collections = await _collectionRepository.GetSomeItemsAsync(id * itemsCount, itemsCount);
            return PartialView("CollectionPage", collections);
        }
    }
}

CollectionsProject/Controllers/ItemController.cs
using CollectionsProject.Extensions;
using CollectionsProject.Models.UserModels;
using CollectionsProject.Repositories.Interfaces;
using CollectionsProject.Services.Interfaces;
using CollectionsProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CollectionsProject.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private readonly IItemRepository _itemRepository;
        private readonly ICollectionRepository _collectionRepository;
        private readonly IItemService _itemService;

        private const int itemCount = 5;

        public ItemController(ICollectionRepository collectionRepository,
            IItemRepository itemRepository, IItemService itemService)
        {
            _collectionRepository = collectionRepository;
            _itemRepository = itemRepository;
            _itemService = itemService;
        }

        [HttpGet]
        public async Task<IActionResult> Create(string id) //collectionId
        {
            var collection = await _collectionRepository.GetItemIncludeFieldsAsync(id);
            if (collection == null)
                return NotFound();
            if (!this.HasAccess(collection.User.UserName))
                return Forbid();
            var model = _itemService.CreateItemViewModel(collection);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(ItemViewModel model) //collectionId
        {
            if (ModelState.IsValid)
            {
                var collection = await _collectionRepository.GetItemIncludeFieldsAsync(model.CollectionId);
                if (collection == null)
                    return NotFound();
                if (!this.HasAccess(collection.User.UserName))
                    return Forbid();
                await _itemService.CreateNewItem(model, collection);
            }
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> ItemsPagination(string collectionId, int id = 0, 
            string sortRule = "Name", string searchString = "")
        {
            var items = await _itemRepository.Filter(id * itemCount, itemCount, collectionId, searchString);
            if (items != null) //skip sort if nothing was found
                items = _itemService.SortItems(items, sortRule);
            return PartialView(items);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(string id)
        {
            var item = await _itemRepository.GetItemAsync(id);
            if (item == null)
                return NotFound();
            if (!this.HasAccess(item.Collection.User.UserName))
                return Forbid();
            _itemRepository.Delete(item);
            await _itemRepository.SaveChangesAsync();
            return Ok();
        }

        //item page with comments
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ItemPage(string id)
        {
            var item = await _itemService.GetAllItemFieldsAsync(id);
            if (item == null)
                return NotFound();
            ViewBag.CurrentUserName = "";
            if (User.Identity!.IsAuthenticated) //for displaying comment form
                ViewBag.CurrentUserName = User.Identity.Name;
            return View(item);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            var item = await _itemService.GetAllItemFieldsAsync(id);
            if (item == null)
                return NotFound();
            if (!this.HasAccess(item.Collection.User.UserName))
                return Forbid();
            var itemViewModel = _itemService.CreateItemViewModel(item);
            return View(itemViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Update(ItemViewModel model)
        {
            if (ModelState.IsValid)
            {
                var item = await _itemService.GetAllItemFieldsAsync(model.ItemId);
                if (item == null)
                    return NotFound();
                if (!this.HasAccess(item.Collection.User.UserName))
                    return Forbid();
                await _itemService.UpdateItem(model, item);
                return RedirectToAction("CollectionItems", "Collection", new { id = model.CollectionId });
            }
            return View(model);
        }

        //add new tag in update or create operations
        [HttpPost]
        public IActionResult AddTagToItem(int i = 0) => PartialView("TagPartial", i);
    }
}

CollectionsProject/Views/Collection/AddNewField.cshtml
@model int
<tr>
    <td><select class="form-select" id="CustomFields[@Model].FieldType" name="CustomFields[@Model].FieldType" asp-items="Html.GetEnumSelectList<CollectionFieldType>()"></select></td>
    <td>
        <input style="width:100%" autocomplete="none" id="CustomFields[@Model].Name" name="CustomFields[@Model].Name" maxlength="15" required>
    </td>
</tr>

CollectionsProject/Views/Collection/CollectionItems.cshtml
@model Collection
@{
    ViewBag.JsPath = "js/scrollingItem.min.js";
    ViewBag.CssPath = "css/collection-view-page.min.css";
    bool isCurrUser = User.Identity!.Name == Model.User.UserName;
    int CountItems = ViewBag.ItemPerPage;
}
@{
    if (isCurrUser || User.IsInRole("Admin"))
    {
        @section Create
        {

        <li class="nav-item">
            <a class="nav-link" asp-controller="Item" asp-action="Create" asp-route-id="@Model.CollectionId">@Loc["Create_Item"]</a>
        </li>
    }
        @section CreatePopUp
        {

        <li class="pop-up-item">
            <a class="pop-up-link" asp-controller="Item" asp-action="Create" asp-route-id="@Model.CollectionId">@Loc["Create_Item"]</a>
        </li>
    }
    }

}
<div class="container">
    <div class="row">
        <div id="@Model.CollectionId" class="bg-light collection-item col-8">
            <div class="row">
                <div class="collection-info col-12  col-md-8">
                    <div class="collection-text-info">
                        <div class="collection-name">
                            <span>@Loc["Name"]</span>
                            <span class="text-name text-warning">@Model.Name</span>

                        </div>
                        <div class="collection-author">
                            <span>@Loc["Author"]</span>
                            <span class="text-warning">@Model.User.UserName</span>
                        </div>
                        <p class="collection-theme text-success">@Model.Type</p>
                        <div class="collection-description">
                            <markdown normalize-whitespace="true">
                                @Model.Description
                            </markdown>
                        </div>
                    </div>
                </div>
                <div class="collection-image col-12 col-md-4">
                    <img class="collection-photo" src="~/images/@Model.Image" alt="image">
                </div>
            </div>
        </div>
    </div>
    @{
        if (CountItems > 0)
        {
            <div class="filter-form row d-flex justify-content-center">
                <div class="filter-wrapper col-md-8 col-lg-6 col-12">
                    <input type="text" class="form-control" maxlength="15" id="filter-input" placeholder="@Loc["Search"]..." autocomplete="off">
                    <button class="btn-success" id="btn-filter"><i class="fa fa-search" aria-hidden="true"></i></button>
                </div>
            </div>
            <div id="item-list" class="flex-column-container container">
                <div class="row overflow-table">
                    <table class="col-8 table-scroll table-collection-list table table-hover table-bordered text-center">
                        <thead class="bg-info">
                            <tr>
                                <th class="attribSort" data-sort="Name">@Loc["Name_Table"]</th>
                                @{
                                    foreach (var field in Model.AddFields)
                                    {
                                        if (field.Type == CollectionFieldType.stringField || field.Type == CollectionFieldType.dateField)
                                        {
                                            <th class="attribSort" data-sort="@field.Name">@field.Name</th>
                                        }

                                    }
                                    <th>@Loc["Action"]</th>
                                }
                            </tr>
                        </thead>
                        <tbody class="table-scroll-body bg-light" id="tableBody">
                        </tbody>
                    </table>
                    <h2 id="item-not-found" class="col-8 Not-Found-Item bg-light">@Loc["No Result"]</h2>
                </div>
                @await Html.PartialAsync("~/Views/Pagination.cshtml",CountItems)
            </div>
        }
        else
        {
            <div style="margin-top:100px" class="col-12 row center-container">
                <h1 class="text-center">@Loc["No Items"]</h1>
            </div>
        }
    }
</div>

CollectionsProject/Views/Collection/CollectionList.cshtml
@{
    ViewBag.JsPath = "js/collection-view-page.min.js";
    ViewBag.CssPath = "css/collection-view-page.min.css";
}
<div class="container">
    <h1 class="text-center">@Loc["Collection List"]</h1>
    <div id="collection-list" class="container-fluid">
    </div>
</div>
@await Html.PartialAsync("Update")
@section Scripts{
    <script>
        loadItems("/Collection/CollectionPage/", '#collection-list');
        $(window).scroll(function () {
            if ((Math.trunc($(window).scrollTop())) === $(document).height() - $(window).height()) {
                loadItems("/Collection/CollectionPage/", '#collection-list');
            }
        });
    </script>
}

CollectionsProject/Views/Collection/CollectionPage.cshtml
@model IEnumerable<Collection>
@{
    bool isAdmin = User.IsInRole("Admin");
}
@{
    if (Model != null)
    {
        foreach (var collection in Model)
        {
            <div id="@collection.CollectionId" class="collection-item col-8 bg-light">
                <div class="row">
                    <div class="collection-info col-12  col-md-8">
                        <div class="collection-text-info">
                            <div class="collection-name">
                                <span>@Loc["Name"]</span>
                                <span class="text-name text-warning">@collection.Name</span>
                                <a class="d-block" asp-controller="Collection" asp-action="CollectionItems" asp-route-id="@collection.CollectionId">@Loc["View"]</a>
                            </div>
                            <div class="collection-author">
                                <span>@Loc["Author"]</span>
                                <span class="text-warning">@collection.User.UserName</span>
                            </div>
                            <p class="collection-theme text-success">@collection.Type</p>
                            <div class="collection-description">
                                <markdown normalize-whitespace="true">
                                    @collection.Description
                                </markdown>
                            </div>
                        </div>
                        @{
                            if (isAdmin || User.Identity.Name == collection.User.UserName)
                            {
                                <div class="form-group">
                                    <button onclick="deleteCollection(event)" class="btn-delete btn-danger text-white">@Loc["Delete"]</button>
                                    <button onclick="updateCollection(event)" class="btn-update btn-primary text-white">@Loc["Update"]</button>
                                </div>
                            }
                        }
                    </div>
                    <div class="collection-image col-12 col-md-4">
                        <img class="collection-photo" src="~/images/@collection.Image" alt="image">
                    </div>
                </div>
            </div>
        }
    }
}

CollectionsProject/Views/Collection/Create.cshtml
@model CollectionViewModel
@{
    ViewBag.CssPath = "css/addCollectionForm.min.css";
    ViewBag.JsPath = "js/addCollection.min.js";
}
<div class="add_collection_cont container">
    <div class="row" style="width:100%">
        <form method="POST" enctype="multipart/form-data" asp-action="Create">
            <div class="collection_wrapper">
                <div class="image_wrapper col-md-6 col-12">
                    <div class="input__wrapper">
                        <input name="formFile" type="file" id="input__file" class="input input__file" accept=".png, .jpg, .jpeg">
                        <label for="input__file" class="input__file-button">
                            <p class="input__file-icon-wrapper"><i class="fa fa-folder-o" aria-hidden="true"></i></p>
                            <span class="input__file-button-text">@Loc["Choose a file"]</span>
                        </label>
                    </div>
                    <img src="~/images/noPhoto.jpg" alt="image" id="image-photo" class="photo" />
                </div>
                <div class="text_wrapper col-md-6 col-12">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <div class="form-group">
                            <label asp-for="Name" class="text_label">@Loc["Collection Name"]</label>
                            <input type="text" asp-for="Name" class="input_form" autocomplete="none">
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="text_label">@Loc["Description"]</label>
                            <textarea asp-for="Description" class="input_form" autocomplete="none"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Type" class="text_label">@Loc["Collection Type"]</label>
                            <select class="form-select" asp-for="Type" asp-items="Html.GetEnumSelectList<CollectionType>()"></select>
                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                        <div class="form-group form-table">
                            <label class="text_label">@Loc["Custom Fields"]</label>
                            <div class="btns-fields">
                                <input type="button" id="btn-add-field" class="btn-app btn-primary" value="@Loc["Add Field"]" />
                                <input type="button" id="btn-remove-field" class="btn-app btn-danger" value="@Loc["Remove Field"]">
                            </div>
                            <div class="overflow-table overflow-collection-table">
                                <table class="table-scroll table table-hover table-bordered">
                                    <thead class="thead">
                                        <tr><th>@Loc["Type"]</th><th>@Loc["Name"]</th></tr>
                                    </thead>
                                    <tbody id="table-body" class="table-scroll-body bg-light info-table">
                                        @await Html.PartialAsync("AddNewField",0)
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <input type="submit" value="@Loc["Send"]" id="btn-send" name="submit" class="btn-primary button_send">
                </div>
            </div>
        </form>
    </div>
</div>

CollectionsProject/Views/Collection/Index.cshtml
@{
    ViewBag.JsPath = "js/collection-view-page.min.js";
    ViewBag.CssPath = "css/collection-view-page.min.css";
}
@section Create{
    <li class="nav-item">
        <a class="nav-link" asp-controller="Collection" asp-action="Create">@Loc["Create"]</a>
    </li>
 }
    @section CreatePopUp{
    <li class="pop-up-item">
        <a class="pop-up-link" asp-controller="Collection" asp-action="Create">@Loc["Create"]</a>
    </li>
 }
    <div class="container">
        <h1 class="text-center">@User.Identity.Name @Loc["Collections"]</h1>
        <div id="collection-list" class="container-fluid">
        </div>
    </div>
    @await Html.PartialAsync("Update")
    @section Scripts{
    <script>
        loadItems("/Collection/PersonalPage/", '#collection-list');
        $(window).scroll(function () {
            if ((Math.trunc($(window).scrollTop())) === $(document).height() - $(window).height()) {
                loadItems("/Collection/PersonalPage/", '#collection-list');
            }
        });
    </script>
    }

CollectionsProject/Views/Collection/Update.cshtml
@model CollectionViewModel
<div id="update_col_cont" style="display:none" class="update_col_cont container">
    <div style="height:95%" class="row">
        <div id="update-hide" class="cross-wrapper container-fluid"><i class="fa fa-times" aria-hidden="true"></i></div>
        <form method="POST" enctype="multipart/form-data" data-ajax="true" data-ajax-method="POST" data-ajax-success="SuccessUpdate" asp-controller="Collection" asp-action="Update" style="min-height:100%">
            <div id="collection-wrapper" class="collection_wrapper">
                <div class="image_wrapper col-4">
                    <div class="input__wrapper">
                        <input name="formFile" type="file" id="input__file" class="input input__file" accept=".png, .jpg, .jpeg">
                        <label for="input__file" class="input__file-button">
                            <p class="input__file-icon-wrapper"><i class="fa fa-folder-o" aria-hidden="true"></i></p>
                            <span class="input__file-button-text">@Loc["Choose a file"]</span>
                        </label>
                        <input asp-for="Id" type="hidden" />
                    </div>
                    <img src="~/images/noPhoto.jpg" alt="image" id="image-photo" style="max-height: 80vh" class="photo" />
                </div>
                <div class="text_wrapper col-8">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="text_label">@Loc["Collection Name"]</label>
                        <input type="text" asp-for="Name" class="input_form" autocomplete="none" maxlength="30" required>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="text_label">@Loc["Description"]</label>
                        <textarea asp-for="Description" class="input_form" autocomplete="none" maxlength="300" required></textarea>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Type" class="text_label">@Loc["Collection Type"]</label>
                        <select id="selector-type" class="form-select" asp-for="Type" asp-items="Html.GetEnumSelectList<CollectionType>()"></select>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <input type="submit" value="@Loc["Update"]" id="btn-send" name="submit" class="btn-primary button_send">
                </div>
            </div>
        </form>
    </div>
</div>